apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    io.apiida_aagm.service: aagmdb
  name: aagmdb
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    io.apiida_aagm.service: aagmdb
status:
  loadBalancer: {}
