apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.apiida_aagm.service: aagm-claim0
  name: aagm-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
#  storageClassName: "fast"
status: {}
