apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: null
  labels:
    io.apiida_aagm.service: prometheus-pushgateway
  name: prometheus-pushgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.apiida_aagm.service: prometheus-pushgateway
  strategy: {}
  template:
    metadata:
      annotations:
      creationTimestamp: null
      labels:
        io.apiida_aagm.service: prometheus-pushgateway
    spec:
      containers:
        - image: prom/pushgateway
          name: prometheus-pushgateway
          resources: {}
      restartPolicy: Always
status: {}
