apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    io.apiida_aagm.service: prometheus-pushgateway
  name: prometheus-pushgateway
spec:
  ports:
    - name: "9091"
      port: 9091
      targetPort: 9091
  selector:
    io.apiida_aagm.service: prometheus-pushgateway
status:
  loadBalancer: {}
